package swap

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/desktopgame/llama-launcher/internal/profile"
	"github.com/desktopgame/llama-launcher/internal/runtime"
	"github.com/desktopgame/llama-launcher/internal/workspace"
)

const (
	groupResident = "resident"
	groupOnDemand = "on-demand"
)

// GenerateConfig builds a llama-swap config.yaml from a workspace and its profiles.
// It writes the file to a temp directory and returns the path.
func GenerateConfig(
	ws *workspace.Workspace,
	profMgr *profile.Manager,
	rtMgr *runtime.Manager,
	port int,
) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by llama-launcher\n")
	b.WriteString("healthCheckTimeout: 120\n")
	b.WriteString("logLevel: info\n")
	b.WriteString("logToStdout: both\n\n")

	// models section
	b.WriteString("models:\n")

	var residentMembers []string
	var onDemandMembers []string

	startPort := port + 1
	for i, entry := range ws.Entries {
		prof, err := profMgr.Load(entry.ProfileName)
		if err != nil {
			return "", fmt.Errorf("failed to load profile %q: %w", entry.ProfileName, err)
		}

		serverPath, err := rtMgr.ServerPath(prof.RuntimeDirName)
		if err != nil {
			return "", fmt.Errorf("failed to find server for runtime %q: %w", prof.RuntimeDirName, err)
		}

		backendPort := startPort + i
		args := prof.BuildArgs(backendPort)
		// normalize backslashes to forward slashes for YAML compatibility
		serverPathNorm := filepath.ToSlash(serverPath)
		var argsNorm []string
		for _, a := range args {
			argsNorm = append(argsNorm, filepath.ToSlash(a))
		}
		cmd := fmt.Sprintf("%s %s", serverPathNorm, strings.Join(argsNorm, " "))

		if entry.Resident {
			residentMembers = append(residentMembers, entry.ProfileName)
		} else {
			onDemandMembers = append(onDemandMembers, entry.ProfileName)
		}

		fmt.Fprintf(&b, "  \"%s\":\n", entry.ProfileName)
		fmt.Fprintf(&b, "    cmd: \"%s\"\n", strings.ReplaceAll(cmd, "\"", "\\\""))
		fmt.Fprintf(&b, "    proxy: \"http://127.0.0.1:%d\"\n", backendPort)
		fmt.Fprintf(&b, "    ttl: %d\n", entry.TTL)
	}

	// groups section — use members to assign models to groups
	b.WriteString("\ngroups:\n")
	if len(residentMembers) > 0 {
		fmt.Fprintf(&b, "  %s:\n", groupResident)
		b.WriteString("    swap: false\n")
		b.WriteString("    exclusive: false\n")
		b.WriteString("    persistent: true\n")
		b.WriteString("    members:\n")
		for _, name := range residentMembers {
			fmt.Fprintf(&b, "      - \"%s\"\n", name)
		}
	}
	if len(onDemandMembers) > 0 {
		fmt.Fprintf(&b, "  %s:\n", groupOnDemand)
		b.WriteString("    swap: true\n")
		b.WriteString("    members:\n")
		for _, name := range onDemandMembers {
			fmt.Fprintf(&b, "      - \"%s\"\n", name)
		}
	}

	// write to temp file
	tmpDir, err := os.MkdirTemp("", "llama-launcher-*")
	if err != nil {
		return "", fmt.Errorf("failed to create temp dir: %w", err)
	}

	configPath := filepath.Join(tmpDir, "config.yaml")
	if err := os.WriteFile(configPath, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("failed to write config: %w", err)
	}

	return configPath, nil
}
