package swap

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/desktopgame/llama-launcher/internal/profile"
	"github.com/desktopgame/llama-launcher/internal/runtime"
	"github.com/desktopgame/llama-launcher/internal/workspace"
)

const (
	groupResident = "resident"
	groupOnDemand = "on-demand"
)

// GenerateConfig builds a llama-swap config.yaml from a workspace and its profiles.
// It writes the file to a temp directory and returns the path.
func GenerateConfig(
	ws *workspace.Workspace,
	profMgr *profile.Manager,
	rtMgr *runtime.Manager,
	port int,
) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by llama-launcher\n")
	b.WriteString("healthCheckTimeout: 120\n")
	b.WriteString("logLevel: info\n")
	b.WriteString("logToStdout: true\n\n")

	// models section
	b.WriteString("models:\n")

	startPort := port + 1
	for i, entry := range ws.Entries {
		prof, err := profMgr.Load(entry.ProfileName)
		if err != nil {
			return "", fmt.Errorf("failed to load profile %q: %w", entry.ProfileName, err)
		}

		serverPath, err := rtMgr.ServerPath(prof.RuntimeDirName)
		if err != nil {
			return "", fmt.Errorf("failed to find server for runtime %q: %w", prof.RuntimeDirName, err)
		}

		backendPort := startPort + i
		args := prof.BuildArgs(backendPort)
		cmd := fmt.Sprintf("%s %s", serverPath, strings.Join(args, " "))

		group := groupOnDemand
		if entry.Resident {
			group = groupResident
		}

		fmt.Fprintf(&b, "  %s:\n", entry.ProfileName)
		fmt.Fprintf(&b, "    cmd: \"%s\"\n", cmd)
		fmt.Fprintf(&b, "    proxy: \"http://127.0.0.1:%d\"\n", backendPort)
		fmt.Fprintf(&b, "    ttl: %d\n", entry.TTL)
		fmt.Fprintf(&b, "    group: %s\n", group)
	}

	// groups section
	b.WriteString("\ngroups:\n")
	fmt.Fprintf(&b, "  %s:\n", groupResident)
	b.WriteString("    swap: false\n")
	fmt.Fprintf(&b, "  %s:\n", groupOnDemand)
	b.WriteString("    swap: true\n")

	// write to temp file
	tmpDir, err := os.MkdirTemp("", "llama-launcher-*")
	if err != nil {
		return "", fmt.Errorf("failed to create temp dir: %w", err)
	}

	configPath := filepath.Join(tmpDir, "config.yaml")
	if err := os.WriteFile(configPath, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("failed to write config: %w", err)
	}

	return configPath, nil
}
